# Generated by Django 2.2.7 on 2019-11-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units101', models.IntegerField()),
                ('units102', models.IntegerField()),
                ('units103', models.IntegerField()),
                ('units104', models.IntegerField()),
                ('units105', models.IntegerField()),
                ('units106', models.IntegerField()),
                ('units107', models.IntegerField()),
                ('units108', models.IntegerField()),
                ('units109', models.IntegerField()),
                ('units110', models.IntegerField()),
            ],
        ),
    ]
