# Generated by Django 2.2.7 on 2019-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
